<a href="https://colab.research.google.com/github/LamponeHub/System-Analysis/blob/main/DB_WineReviews.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# @title 🍷 Создание и заполнение базы данных Wine Reviews
# @markdown Этот код создаст SQLite базу данных и заполнит её примерами данных

import sqlite3
import pandas as pd
from IPython.display import display, Markdown

# Создание подключения к базе данных (в памяти)
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

print("✅ База данных создана успешно!")

# @title 📋 Создание таблиц
# @markdown Создание всех необходимых таблиц согласно схеме

# Создание таблицы countries
cursor.execute('''
CREATE TABLE countries (
    country_id INTEGER PRIMARY KEY AUTOINCREMENT,
    country_abbr TEXT,
    latitude REAL,
    longitude REAL,
    country_name TEXT,
    temperature REAL
)
''')

# Создание таблицы provinces
cursor.execute('''
CREATE TABLE provinces (
    province_id INTEGER PRIMARY KEY AUTOINCREMENT,
    province_name TEXT,
    avg_f REAL,
    avg_c REAL
)
''')

# Создание таблицы regions
cursor.execute('''
CREATE TABLE regions (
    region_id INTEGER PRIMARY KEY AUTOINCREMENT,
    region_name TEXT
)
''')

# Создание таблицы wineries
cursor.execute('''
CREATE TABLE wineries (
    winery_id INTEGER PRIMARY KEY AUTOINCREMENT,
    winery_name TEXT
)
''')

# Создание таблицы wine_types
cursor.execute('''
CREATE TABLE wine_types (
    wine_type_id INTEGER PRIMARY KEY AUTOINCREMENT,
    wine_type TEXT
)
''')

# Создание таблицы wines
cursor.execute('''
CREATE TABLE wines (
    wine_id INTEGER PRIMARY KEY AUTOINCREMENT,
    wine_name TEXT,
    country_id INTEGER,
    province_id INTEGER,
    region_id INTEGER,
    winery_id INTEGER,
    wine_type_id INTEGER,
    rating REAL,
    price REAL,
    FOREIGN KEY (country_id) REFERENCES countries(country_id),
    FOREIGN KEY (province_id) REFERENCES provinces(province_id),
    FOREIGN KEY (region_id) REFERENCES regions(region_id),
    FOREIGN KEY (winery_id) REFERENCES wineries(winery_id),
    FOREIGN KEY (wine_type_id) REFERENCES wine_types(wine_type_id)
)
''')

print("✅ Все таблицы созданы успешно!")

# @title 💾 Заполнение данными
# @markdown Вставка примеров данных во все таблицы

# Вставка данных в countries
countries_data = [
    ('US', 37.0902, -95.7129, 'USA', 15.5),
    ('FR', 46.2276, 2.2137, 'France', 12.0),
    ('IT', 41.8719, 12.5674, 'Italy', 14.5),
    ('ES', 40.4637, -3.7492, 'Spain', 15.0),
]
cursor.executemany('INSERT INTO countries (country_abbr, latitude, longitude, country_name, temperature) VALUES (?, ?, ?, ?, ?)', countries_data)

# Вставка данных в provinces
provinces_data = [
    ('California', 65.0, 18.3),
    ('Bordeaux', 58.0, 14.4),
    ('Tuscany', 62.0, 16.7),
    ('Rioja', 60.0, 15.6),
    ('Oregon', 55.0, 12.8),
]
cursor.executemany('INSERT INTO provinces (province_name, avg_f, avg_c) VALUES (?, ?, ?)', provinces_data)

# Вставка данных в regions
regions_data = [
    ('Napa Valley',),
    ('Sonoma',),
    ('Willamette Valley',),
    ('Chianti',),
    ('Piedmont',),
]
cursor.executemany('INSERT INTO regions (region_name) VALUES (?)', regions_data)

# Вставка данных в wineries
wineries_data = [
    ('Opus One',),
    ('Chateau Margaux',),
    ('Antinori',),
    ('Vega Sicilia',),
    ('Screaming Eagle',),
    ('Simple Wine Co.',),
]
cursor.executemany('INSERT INTO wineries (winery_name) VALUES (?)', wineries_data)

# Вставка данных в wine_types
wine_types_data = [
    ('Cabernet Sauvignon',),
    ('Merlot',),
    ('Pinot Noir',),
    ('Chardonnay',),
    ('Sangiovese',),
    ('Tempranillo',),
]
cursor.executemany('INSERT INTO wine_types (wine_type) VALUES (?)', wine_types_data)

# Вставка данных в wines
wines_data = [
    ('Opus One 2018', 1, 1, 1, 1, 1, 96, 400.00),
    ('Chateau Margaux 2015', 2, 2, None, 2, 2, 98, 800.00),
    ('Tignanello 2017', 3, 3, 4, 3, 5, 94, 150.00),
    ('Vega Sicilia Unico 2011', 4, 4, None, 4, 6, 97, 500.00),
    ('Screaming Eagle Cabernet 2019', 1, 1, 1, 5, 1, 99, 3500.00),
    ('Simple Wine Co. Table Wine', 1, 5, 3, 6, 3, 75, 12.00),
    ('Budget Bordeaux', 2, 2, None, None, 2, 80, 15.00),
    ('Oregon Pinot Noir Reserve', 1, 5, 3, None, 3, 91, 45.00),
    ('Chianti Classico', 3, 3, 4, None, 5, 88, 25.00),
    ('Napa Valley Chardonnay', 1, 1, 1, None, 4, 90, 55.00),
    ('Barolo Riserva', 3, None, 5, None, 5, 93, 85.00),
    ('Rioja Gran Reserva', 4, 4, None, None, 6, 92, 65.00),
]
cursor.executemany('''INSERT INTO wines (wine_name, country_id, province_id, region_id, winery_id, wine_type_id, rating, price)
                      VALUES (?, ?, ?, ?, ?, ?, ?, ?)''', wines_data)

conn.commit()
print("✅ Данные успешно загружены!")
print(f"   - Стран: {len(countries_data)}")
print(f"   - Регионов: {len(provinces_data)}")
print(f"   - Областей: {len(regions_data)}")
print(f"   - Виноделен: {len(wineries_data)}")
print(f"   - Типов вин: {len(wine_types_data)}")
print(f"   - Вин: {len(wines_data)}")

# @title 📊 Вопрос 1: Самое дорогое и самое дешевое вино
# @markdown Какая страна производила самое дорогое вино? Какое вино было самым дешевым?

query1_expensive = '''
SELECT
    c.country_name as Страна,
    w.wine_name as Вино,
    w.price as Цена
FROM wines w
JOIN countries c ON w.country_id = c.country_id
ORDER BY w.price DESC
LIMIT 1
'''

query1_cheap = '''
SELECT
    c.country_name as Страна,
    w.wine_name as Вино,
    w.price as Цена
FROM wines w
JOIN countries c ON w.country_id = c.country_id
ORDER BY w.price ASC
LIMIT 1
'''

print("💰 САМОЕ ДОРОГОЕ ВИНО:")
display(pd.read_sql_query(query1_expensive, conn))

print("\n💵 САМОЕ ДЕШЕВОЕ ВИНО:")
display(pd.read_sql_query(query1_cheap, conn))

# @title 🌍 Вопрос 2: Самый популярный сорт вина по странам
# @markdown Определите самый популярный сорт вина по странам

query2 = '''
SELECT
    c.country_name as Страна,
    wt.wine_type as Сорт_вина,
    COUNT(*) as Количество
FROM wines w
JOIN countries c ON w.country_id = c.country_id
JOIN wine_types wt ON w.wine_type_id = wt.wine_type_id
GROUP BY c.country_name, wt.wine_type
ORDER BY c.country_name, Количество DESC
'''

print("🍇 ПОПУЛЯРНОСТЬ СОРТОВ ВИНА ПО СТРАНАМ:")
display(pd.read_sql_query(query2, conn))

# @title ⭐ Вопрос 3: Наилучший рейтинг по областям
# @markdown Вина какой области (province) получают наилучший рейтинг? Более дорогие вина оцениваются выше?

query3_rating = '''
SELECT
    p.province_name as Область,
    ROUND(AVG(w.rating), 2) as Средний_рейтинг,
    COUNT(*) as Количество_вин
FROM wines w
JOIN provinces p ON w.province_id = p.province_id
GROUP BY p.province_name
ORDER BY Средний_рейтинг DESC
'''

query3_correlation = '''
SELECT
    ROUND(AVG(rating), 2) as Общий_средний_рейтинг,
    ROUND(AVG(price), 2) as Средняя_цена,
    ROUND(MIN(rating), 2) as Мин_рейтинг,
    ROUND(MAX(rating), 2) as Макс_рейтинг,
    ROUND(MIN(price), 2) as Мин_цена,
    ROUND(MAX(price), 2) as Макс_цена
FROM wines
'''

print("🏆 РЕЙТИНГ ВИНА ПО ОБЛАСТЯМ:")
display(pd.read_sql_query(query3_rating, conn))

print("\n📈 ОБЩАЯ СТАТИСТИКА (корреляция цены и качества):")
display(pd.read_sql_query(query3_correlation, conn))

# @title 🥇 Вопрос 4: Вина с наилучшим рейтингом
# @markdown Определить, какие вины лидируют по рейтингам

query4_top = '''
SELECT
    w.wine_name as Вино,
    w.rating as Рейтинг,
    w.price as Цена,
    c.country_name as Страна,
    p.province_name as Область,
    wt.wine_type as Сорт
FROM wines w
JOIN countries c ON w.country_id = c.country_id
LEFT JOIN provinces p ON w.province_id = p.province_id
JOIN wine_types wt ON w.wine_type_id = wt.wine_type_id
ORDER BY w.rating DESC
LIMIT 5
'''

print("🏅 ТОП-5 ВИН ПО РЕЙТИНГУ:")
display(pd.read_sql_query(query4_top, conn))

# @title 🏭 Вопрос 5: Лучшие винодельни
# @markdown Какие винодельни производят самые дорогие/высоко оцененные вина?

query5_expensive = '''
SELECT
    win.winery_name as Винодельня,
    ROUND(AVG(w.price), 2) as Средняя_цена,
    MAX(w.price) as Макс_цена,
    COUNT(*) as Количество_вин
FROM wines w
JOIN wineries win ON w.winery_id = win.winery_id
GROUP BY win.winery_name
ORDER by Средняя_цена DESC
'''

query5_rating = '''
SELECT
    win.winery_name as Винодельня,
    ROUND(AVG(w.rating), 2) as Средний_рейтинг,
    MAX(w.rating) as Макс_рейтинг,
    COUNT(*) as Количество_вин
FROM wines w
JOIN wineries win ON w.winery_id = win.winery_id
GROUP BY win.winery_name
ORDER BY Средний_рейтинг DESC
'''

print("💎 ВИНОДЕЛЬНИ С САМЫМИ ДОРОГИМИ ВИНАМИ:")
display(pd.read_sql_query(query5_expensive, conn))

print("\n⭐ ВИНОДЕЛЬНИ С НАИВЫСШИМИ РЕЙТИНГАМИ:")
display(pd.read_sql_query(query5_rating, conn))

# @title 📉 Вопрос 6: Вина с низким рейтингом
# @markdown Какие винодельни/регионы/страны производят вина с самым низким рейтингом?

query6_wineries = '''
SELECT
    win.winery_name as Винодельня,
    ROUND(AVG(w.rating), 2) as Средний_рейтинг,
    MIN(w.rating) as Мин_рейтинг,
    COUNT(*) as Количество
FROM wines w
JOIN wineries win ON w.winery_id = win.winery_id
GROUP BY win.winery_name
ORDER BY Средний_рейтинг ASC
LIMIT 5
'''

query6_countries = '''
SELECT
    c.country_name as Страна,
    ROUND(AVG(w.rating), 2) as Средний_рейтинг,
    MIN(w.rating) as Мин_рейтинг,
    MAX(w.rating) as Макс_рейтинг,
    COUNT(*) as Количество
FROM wines w
JOIN countries c ON w.country_id = c.country_id
GROUP BY c.country_name
ORDER BY Средний_рейтинг ASC
'''

print("📉 ВИНОДЕЛЬНИ С НАИЗКИМ РЕЙТИНГОМ:")
display(pd.read_sql_query(query6_wineries, conn))

print("\n🌍 СТРАНЫ ПО СРЕДНЕМУ РЕЙТИНГУ:")
display(pd.read_sql_query(query6_countries, conn))

# @title 📊 Дополнительная статистика
# @markdown Общее соотношение цена/качество

query_extra = '''
SELECT
    w.wine_name as Вино,
    w.rating as Рейтинг,
    w.price as Цена,
    ROUND((w.rating / CASE WHEN w.price > 0 THEN w.price ELSE 1 END) * 100, 2) as Соотношение_цена_качество,
    c.country_name as Страна
FROM wines w
JOIN countries c ON w.country_id = c.country_id
WHERE w.price > 0
ORDER BY Соотношение_цена_качество DESC
LIMIT 10
'''

print("💡 ЛУЧШЕЕ СООТНОШЕНИЕ ЦЕНА/КАЧЕСТВО:")
display(pd.read_sql_query(query_extra, conn))

# Общая статистика
query_stats = '''
SELECT
    COUNT(*) as Всего_вин,
    ROUND(AVG(rating), 2) as Средний_рейтинг,
    MIN(rating) as Мин_рейтинг,
    MAX(rating) as Макс_рейтинг,
    ROUND(AVG(price), 2) as Средняя_цена,
    MIN(price) as Мин_цена,
    MAX(price) as Макс_цена
FROM wines
'''

print("\n📊 ОБЩАЯ СТАТИСТИКА ПО БАЗЕ:")
display(pd.read_sql_query(query_stats, conn))

print("\n✅ Все запросы выполнены успешно!")

✅ База данных создана успешно!
✅ Все таблицы созданы успешно!
✅ Данные успешно загружены!
   - Стран: 4
   - Регионов: 5
   - Областей: 5
   - Виноделен: 6
   - Типов вин: 6
   - Вин: 12
💰 САМОЕ ДОРОГОЕ ВИНО:

  Страна                           Вино    Цена
0    USA  Screaming Eagle Cabernet 2019  3500.0

💵 САМОЕ ДЕШЕВОЕ ВИНО:

  Страна                        Вино  Цена
0    USA  Simple Wine Co. Table Wine  12.0

🍇 ПОПУЛЯРНОСТЬ СОРТОВ ВИНА ПО СТРАНАМ:

   Страна           Сорт_вина  Количество
0  France              Merlot           2
1   Italy          Sangiovese           3
2   Spain         Tempranillo           2
3     USA          Pinot Noir           2
4     USA  Cabernet Sauvignon           2
5     USA          Chardonnay           1

🏆 РЕЙТИНГ ВИНА ПО ОБЛАСТЯМ:

      Область  Средний_рейтинг  Количество_вин
0  California             95.0               3
1       Rioja             94.5               2
2     Tuscany             91.0               2
3    Bordeaux             89.0               2
4      Oregon             83.0               2

📈 ОБЩАЯ СТАТИСТИКА (корреляция цены и качества):

,Общий_средний_рейтинг,Средняя_цена,Мин_рейтинг,Макс_рейтинг,Мин_цена,Макс_цена
0,91.08,471.0,75.0,99.0,12.0,3500.0

🏅 ТОП-5 ВИН ПО РЕЙТИНГУ:

,Вино,Рейтинг,Цена,Страна,Область,Сорт
0,Screaming Eagle Cabernet 2019,99.0,3500.0,USA,California,Cabernet Sauvignon
1,Chateau Margaux 2015,98.0,800.0,France,Bordeaux,Merlot
2,Vega Sicilia Unico 2011,97.0,500.0,Spain,Rioja,Tempranillo
3,Opus One 2018,96.0,400.0,USA,California,Cabernet Sauvignon
4,Tignanello 2017,94.0,150.0,Italy,Tuscany,Sangiovese

💎 ВИНОДЕЛЬНИ С САМЫМИ ДОРОГИМИ ВИНАМИ:

        Винодельня  Средняя_цена  Макс_цена  Количество_вин
0  Screaming Eagle        3500.0     3500.0               1
1  Chateau Margaux         800.0      800.0               1
2     Vega Sicilia         500.0      500.0               1
3         Opus One         400.0      400.0               1
4         Antinori         150.0      150.0               1
5  Simple Wine Co.          12.0       12.0               1

⭐ ВИНОДЕЛЬНИ С НАИВЫСШИМИ РЕЙТИНГАМИ:

        Винодельня  Средний_рейтинг  Макс_рейтинг  Количество_вин
0  Screaming Eagle             99.0          99.0               1
1  Chateau Margaux             98.0          98.0               1
2     Vega Sicilia             97.0          97.0               1
3         Opus One             96.0          96.0               1
4         Antinori             94.0          94.0               1
5  Simple Wine Co.             75.0          75.0               1

📉 ВИНОДЕЛЬНИ С НАИЗКИМ РЕЙТИНГОМ:

        Винодельня  Средний_рейтинг  Мин_рейтинг  Количество
0  Simple Wine Co.             75.0         75.0           1
1         Antinori             94.0         94.0           1
2         Opus One             96.0         96.0           1
3     Vega Sicilia             97.0         97.0           1
4  Chateau Margaux             98.0         98.0           1

🌍 СТРАНЫ ПО СРЕДНЕМУ РЕЙТИНГУ:

   Страна  Средний_рейтинг  Мин_рейтинг  Макс_рейтинг  Количество
0  France            89.00         80.0          98.0           2
1     USA            90.20         75.0          99.0           5
2   Italy            91.67         88.0          94.0           3
3   Spain            94.50         92.0          97.0           2

💡 ЛУЧШЕЕ СООТНОШЕНИЕ ЦЕНА/КАЧЕСТВО:

,Вино,Рейтинг,Цена,Соотношение_цена_качество,Страна
0,Simple Wine Co. Table Wine,75.0,12.0,625.00,USA
1,Budget Bordeaux,80.0,15.0,533.33,France
2,Chianti Classico,88.0,25.0,352.00,Italy
3,Oregon Pinot Noir Reserve,91.0,45.0,202.22,USA
4,Napa Valley Chardonnay,90.0,55.0,163.64,USA
5,Rioja Gran Reserva,92.0,65.0,141.54,Spain
6,Barolo Riserva,93.0,85.0,109.41,Italy
7,Tignanello 2017,94.0,150.0,62.67,Italy
8,Opus One 2018,96.0,400.0,24.00,USA
9,Vega Sicilia Unico 2011,97.0,500.0,19.40,Spain

📊 ОБЩАЯ СТАТИСТИКА ПО БАЗЕ:

,Всего_вин,Средний_рейтинг,Мин_рейтинг,Макс_рейтинг,Средняя_цена,Мин_цена,Макс_цена
0,12,91.08,75.0,99.0,471.0,12.0,3500.0

✅ Все запросы выполнены успешно!